# Generated by scripts/publish-packages.sh from
# packaging/templates/swift-salamander.rb.tmpl for Swift Salamander 0.8.69.
# Edit the template, not this file.
cask "swift-salamander" do
  version "0.8.69"
  sha256 "cd11c84f41d0ed3974e087751623c0e9e9aa71b163a001f163db2881421819d7"

  url "https://cdn.codesurfer.ch/swift-salamander/SwiftSalamander_#{version}_arm64.dmg",
      verified: "cdn.codesurfer.ch/swift-salamander/"
  name "Swift Salamander"
  desc "Dual-pane file manager for local folders and network storage"
  homepage "https://salamander.codesurfer.ch/"

  # The updater manifest is the version's home. Reading it here means
  # `brew livecheck` and a future official cask both learn about a release
  # from the same file the app itself reads, so the three can never disagree.
  livecheck do
    url "https://cdn.codesurfer.ch/swift-salamander/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # No `auto_updates true`. The app does carry its own updater, and that line
  # would tell Homebrew to step back and leave upgrades to it. The owner
  # reversed that on 2026-08-27 (ledger L1): somebody who installed with
  # Homebrew expects `brew upgrade` to upgrade it, and being told "that one is
  # special, pass --greedy" is a worse surprise than two updaters offering the
  # same version. The in-app updater still works; whichever gets there first
  # installs the same notarized bundle.
  depends_on macos: :ventura
  depends_on arch: :arm64

  app "Swift Salamander.app"

  # The real on-disk footprint of a used install, listed rather than guessed.
  # Application Support holds the licence file and the favourites, so `zap`
  # takes the licence with it. That is what `zap` means; `brew uninstall`
  # without it leaves this list alone.
  zap trash: [
    "~/Library/Application Scripts/ch.raciborski.swiftsalamander",
    "~/Library/Application Support/ch.raciborski.swiftsalamander",
    "~/Library/Caches/ch.raciborski.swiftsalamander",
    "~/Library/Containers/ch.raciborski.swiftsalamander",
    "~/Library/Logs/ch.raciborski.swiftsalamander",
    "~/Library/WebKit/ch.raciborski.swiftsalamander",
  ]
end
