# Generated by scripts/publish-packages.sh from
# packaging/templates/swift-salamander.rb.tmpl for Swift Salamander 0.8.63.
# Edit the template, not this file.
cask "swift-salamander" do
  version "0.8.63"
  sha256 "a9a01f9a8bd39c81ba759214aaeba26f9651aa898be18081813ab0041d62d800"

  url "https://cdn.codesurfer.ch/swift-salamander/SwiftSalamander_#{version}_arm64.dmg",
      verified: "cdn.codesurfer.ch/swift-salamander/"
  name "Swift Salamander"
  desc "Dual-pane file manager for local folders and network storage"
  homepage "https://salamander.codesurfer.ch/"

  # The updater manifest is the version's home. Reading it here means
  # `brew livecheck` and a future official cask both learn about a release
  # from the same file the app itself reads, so the three can never disagree.
  livecheck do
    url "https://cdn.codesurfer.ch/swift-salamander/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # The app updates itself. Without this line `brew upgrade` would replace a
  # bundle the in-app updater had already moved forward, so two mechanisms
  # would be writing the same directory. With it, Homebrew steps back and
  # `brew upgrade --greedy` is the way to ask it to act anyway.
  auto_updates true
  depends_on macos: :ventura
  depends_on arch: :arm64

  app "Swift Salamander.app"

  # The real on-disk footprint of a used install, listed rather than guessed.
  # Application Support holds the licence file and the favourites, so `zap`
  # takes the licence with it. That is what `zap` means; `brew uninstall`
  # without it leaves this list alone.
  zap trash: [
    "~/Library/Application Scripts/ch.raciborski.swiftsalamander",
    "~/Library/Application Support/ch.raciborski.swiftsalamander",
    "~/Library/Caches/ch.raciborski.swiftsalamander",
    "~/Library/Containers/ch.raciborski.swiftsalamander",
    "~/Library/Logs/ch.raciborski.swiftsalamander",
    "~/Library/WebKit/ch.raciborski.swiftsalamander",
  ]
end
